version: "3"
services:
  web:
    container_name: ToxicityMonitorApp
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./tests/:/app/tests

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkinsCont
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_dat:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_dat:
