version: "3"
services:
  web:
    container_name: ToxicityMonitorApp
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./tests/:/app/tests

  jenkins:
    container_name: jenkinsCont
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/jenkins_data"
